name: pg
channels:
  - gimli
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.3=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.10.11=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - curl=7.87.0=hdc1c0ab_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - double-conversion=3.2.0=h27087fc_1
  - eigen=3.3.7=hd09550d_1
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_105
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h7b6447c_0
  - gl2ps=1.4.2=h70c0345_1
  - glew=2.1.0=h295c915_3
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.33=h166bdaf_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=70.1=h27087fc_0
  - idna=3.4=py39h06a4308_0
  - imageio=2.19.3=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.7.0=py39h06a4308_0
  - jack=1.9.21=h583fa2b_2
  - jedi=0.18.1=py39h06a4308_1
  - jpeg=9e=h7f8727e_0
  - jsoncpp=1.9.5=h4bd325d_1
  - jupyter_client=7.4.8=py39h06a4308_0
  - jupyter_core=5.1.1=py39h06a4308_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_had23c3d_0
  - libclang13=15.0.7=default_h3e3d535_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=hdc1c0ab_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.2=h27087fc_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libglu=9.0.0=hf484d3e_1
  - libgomp=12.2.0=h65d4601_19
  - libgpg-error=1.46=h620e276_0
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_0
  - libnetcdf=4.8.1=nompi_h261ec11_106
  - libnghttp2=1.51.0=hff17c54_0
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpq=15.1=hb675445_3
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.5.0=hecacb30_0
  - libtool=2.4.7=h27087fc_0
  - libudev1=252=h166bdaf_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.17.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=h7463322_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - loguru=0.5.3=py39h06a4308_3
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.5.1=py39hf3d152e_0
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - metis=5.1.0=hf484d3e_4
  - mpfr=4.1.0=h9202a9a_1
  - mpg123=1.31.2=hcb278e6_0
  - multidict=6.0.2=py39h5eee18b_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.8.1=hc379101_1
  - nlohmann_json=3.10.5=h295c915_0
  - nspr=4.35=h27087fc_0
  - nss=3.82=he02c5a1_0
  - numpy=1.20.3=py39hd249d9e_2
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openh264=2.3.1=h27087fc_1
  - openssl=3.0.7=h0b41bf4_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=22.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pgcore=1.3.0=np120py39h3fd9d12_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py39hace64e9_1
  - pip=22.3.1=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=2.5.2=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - proj=9.1.1=h8ffa02c_2
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.11.4=h295c915_1
  - pulseaudio=16.1=ha8d29e2_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygimli=1.3.1=py_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h18e9c17_2
  - pyqt5-sip=12.11.0=py39h5a03fae_2
  - pysocks=1.7.1=py39h06a4308_0
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.15=hba424b6_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=3_cp39
  - pyvista=0.34.2=pyhd8ed1ab_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.6=h602db52_6
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - scipy=1.10.0=py39h7360e5f_0
  - scooby=0.7.0=pyhd8ed1ab_1
  - setuptools=65.6.3=py39h06a4308_0
  - sip=6.7.5=py39h5a03fae_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - suitesparse=5.10.1=h9e50725_1
  - svt-av1=1.4.1=hcb278e6_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.7.0=h924138e_1
  - tbb-devel=2021.7.0=h924138e_1
  - tetgen=1.6.0=he1b5a44_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - urllib3=1.26.14=py39h06a4308_0
  - utfcpp=3.2.1=h06a4308_0
  - vtk=9.2.5=qt_py39h99e95b5_202
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wslink=1.10.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.10=h5eee18b_1
  - yarl=1.8.1=py39h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - altair==4.2.0
      - blinker==1.5
      - cachetools==5.3.0
      - click==8.1.3
      - gitdb==4.0.10
      - gitpython==3.1.30
      - importlib-metadata==6.0.0
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - markdown-it-py==2.1.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - pandas==1.5.3
      - protobuf==3.20.3
      - pyarrow==10.0.1
      - pydeck==0.8.0
      - pympler==1.0.1
      - pyrsistent==0.19.3
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - rich==13.2.0
      - semver==2.13.0
      - smmap==5.0.0
      - streamlit==1.17.0
      - toolz==0.12.0
      - tzdata==2022.7
      - tzlocal==4.2
      - validators==0.20.0
      - watchdog==2.2.1
      - zipp==3.11.0
