name: pg
channels:
  - gimli
  - defaults
dependencies:
  - pygimli=1.3.1
  - ncurses
  - debugpy
  - jupyter_core
  - libsodium
  - executing
  - libffi
  - libzlib
  - pygments
  - stack_data
  - tzdata
  - psutil
  - pure_eval
  - _openmp_mutex
  - libsqlite
  - pickleshare
  - ptyprocess
  - xz
  - zlib
  - ld_impl_linux-64
  - _libgcc_mutex
  - prompt-toolkit
  - libgomp
  - libgcc-ng
  - decorator
  - bzip2
  - libuuid
  - certifi
  - ca-certificates
  - matplotlib-inline
  - parso
  - python=3.9
  - platformdirs
  - tk
  - pip
  - packaging
  - tornado
  - setuptools
  - pexpect
  - traitlets
  - wcwidth
  - zeromq
  - libstdcxx-ng
  - python-dateutil
  - ipython
  - libnsl
  - jedi
  - entrypoints
  - comm
  - pyzmq
  - jupyter_client
  - openssl
  - backcall
  - six
  - wheel
  - nest-asyncio
  - readline
  - asttokens
  - ipykernel
prefix: /home/edsaa/.conda/envs/pg
